/**
 * cloudwpss23-openapi-cyan
 * OpenAPI Reference für das CloudWP der HAW Hamburg für das SommerSemster 2023
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The GetApiExternal200Response model module.
 * @module model/GetApiExternal200Response
 * @version 1.0
 */
class GetApiExternal200Response {
    /**
     * Constructs a new <code>GetApiExternal200Response</code>.
     * @alias module:model/GetApiExternal200Response
     */
    constructor() { 
        
        GetApiExternal200Response.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GetApiExternal200Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetApiExternal200Response} obj Optional instance to populate.
     * @return {module:model/GetApiExternal200Response} The populated <code>GetApiExternal200Response</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetApiExternal200Response();

            if (data.hasOwnProperty('pong')) {
                obj['pong'] = ApiClient.convertToType(data['pong'], Object);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>GetApiExternal200Response</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>GetApiExternal200Response</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * @member {Object} pong
 */
GetApiExternal200Response.prototype['pong'] = undefined;






export default GetApiExternal200Response;

