/**
 * cloudwpss23-openapi-cyan
 * OpenAPI Reference für das CloudWP der HAW Hamburg für das SommerSemster 2023
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PatchUsersUserIdRequest model module.
 * @module model/PatchUsersUserIdRequest
 * @version 1.0
 */
class PatchUsersUserIdRequest {
    /**
     * Constructs a new <code>PatchUsersUserIdRequest</code>.
     * @alias module:model/PatchUsersUserIdRequest
     */
    constructor() { 
        
        PatchUsersUserIdRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PatchUsersUserIdRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PatchUsersUserIdRequest} obj Optional instance to populate.
     * @return {module:model/PatchUsersUserIdRequest} The populated <code>PatchUsersUserIdRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PatchUsersUserIdRequest();

            if (data.hasOwnProperty('firstName')) {
                obj['firstName'] = ApiClient.convertToType(data['firstName'], Object);
            }
            if (data.hasOwnProperty('lastName')) {
                obj['lastName'] = ApiClient.convertToType(data['lastName'], Object);
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], Object);
            }
            if (data.hasOwnProperty('dateOfBirth')) {
                obj['dateOfBirth'] = ApiClient.convertToType(data['dateOfBirth'], Object);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PatchUsersUserIdRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PatchUsersUserIdRequest</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * @member {Object} firstName
 */
PatchUsersUserIdRequest.prototype['firstName'] = undefined;

/**
 * @member {Object} lastName
 */
PatchUsersUserIdRequest.prototype['lastName'] = undefined;

/**
 * If a new email is given, the user's email verified property will be set to false.
 * @member {Object} email
 */
PatchUsersUserIdRequest.prototype['email'] = undefined;

/**
 * @member {Object} dateOfBirth
 */
PatchUsersUserIdRequest.prototype['dateOfBirth'] = undefined;






export default PatchUsersUserIdRequest;

