/**
 * cloudwpss23-openapi-cyan
 * OpenAPI Reference für das CloudWP der HAW Hamburg für das SommerSemster 2023
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PostUserRequest model module.
 * @module model/PostUserRequest
 * @version 1.0
 */
class PostUserRequest {
    /**
     * Constructs a new <code>PostUserRequest</code>.
     * @alias module:model/PostUserRequest
     * @param firstName {Object} 
     * @param lastName {Object} 
     * @param email {Object} 
     * @param dateOfBirth {Object} 
     */
    constructor(firstName, lastName, email, dateOfBirth) { 
        
        PostUserRequest.initialize(this, firstName, lastName, email, dateOfBirth);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, firstName, lastName, email, dateOfBirth) { 
        obj['firstName'] = firstName;
        obj['lastName'] = lastName;
        obj['email'] = email;
        obj['dateOfBirth'] = dateOfBirth;
    }

    /**
     * Constructs a <code>PostUserRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PostUserRequest} obj Optional instance to populate.
     * @return {module:model/PostUserRequest} The populated <code>PostUserRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PostUserRequest();

            if (data.hasOwnProperty('firstName')) {
                obj['firstName'] = ApiClient.convertToType(data['firstName'], Object);
            }
            if (data.hasOwnProperty('lastName')) {
                obj['lastName'] = ApiClient.convertToType(data['lastName'], Object);
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], Object);
            }
            if (data.hasOwnProperty('dateOfBirth')) {
                obj['dateOfBirth'] = ApiClient.convertToType(data['dateOfBirth'], Object);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PostUserRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PostUserRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of PostUserRequest.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }

        return true;
    }


}

PostUserRequest.RequiredProperties = ["firstName", "lastName", "email", "dateOfBirth"];

/**
 * @member {Object} firstName
 */
PostUserRequest.prototype['firstName'] = undefined;

/**
 * @member {Object} lastName
 */
PostUserRequest.prototype['lastName'] = undefined;

/**
 * @member {Object} email
 */
PostUserRequest.prototype['email'] = undefined;

/**
 * @member {Object} dateOfBirth
 */
PostUserRequest.prototype['dateOfBirth'] = undefined;






export default PostUserRequest;

