/**
 * cloudwpss23-openapi-cyan
 * OpenAPI Reference für das CloudWP der HAW Hamburg für das SommerSemster 2023
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Cloudwpss23OpenapiCyan);
  }
}(this, function(expect, Cloudwpss23OpenapiCyan) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Cloudwpss23OpenapiCyan.PatchUsersUserIdRequest();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('PatchUsersUserIdRequest', function() {
    it('should create an instance of PatchUsersUserIdRequest', function() {
      // uncomment below and update the code to test PatchUsersUserIdRequest
      //var instance = new Cloudwpss23OpenapiCyan.PatchUsersUserIdRequest();
      //expect(instance).to.be.a(Cloudwpss23OpenapiCyan.PatchUsersUserIdRequest);
    });

    it('should have the property firstName (base name: "firstName")', function() {
      // uncomment below and update the code to test the property firstName
      //var instance = new Cloudwpss23OpenapiCyan.PatchUsersUserIdRequest();
      //expect(instance).to.be();
    });

    it('should have the property lastName (base name: "lastName")', function() {
      // uncomment below and update the code to test the property lastName
      //var instance = new Cloudwpss23OpenapiCyan.PatchUsersUserIdRequest();
      //expect(instance).to.be();
    });

    it('should have the property email (base name: "email")', function() {
      // uncomment below and update the code to test the property email
      //var instance = new Cloudwpss23OpenapiCyan.PatchUsersUserIdRequest();
      //expect(instance).to.be();
    });

    it('should have the property dateOfBirth (base name: "dateOfBirth")', function() {
      // uncomment below and update the code to test the property dateOfBirth
      //var instance = new Cloudwpss23OpenapiCyan.PatchUsersUserIdRequest();
      //expect(instance).to.be();
    });

  });

}));
